### ISSUE TITLE
dialog 'Add' layout

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_snippets#17]
we have 'New...' listbox item which is like a button!
so why not to place the normal button 'New...' (better name it 'Add...') ?

```
[.............................] [Add...] [Delete...]
```
@halfbrained

**Comment by halfbrained** [comment]
Ok (not sure why I did it this way :D )

**Comment by halfbrained** [comment]
fixed 
![snipman](https://user-images.githubusercontent.com/74829192/108726651-54695000-7530-11eb-9cf4-d87e94e19eff.png)

**Comment by Alexey-T** [comment]
thanks; I like it.

@kvichans @OlehL any feedback? code is in forked repo.
