### ISSUE TITLE
bug with Python snippet, with multi-selections after tab-stop jumps

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_snippets#20]
lexer python. snippet is
![Screenshot from 2021-02-23 11-39-39](https://user-images.githubusercontent.com/4154978/108819377-d5295a00-75cb-11eb-8f5d-57875efc2632.png)

insert it. now press TAB to move to tab stops.
after jump to 'k' selections are bad! 2nd 'k' is NOT SELECTED.

after jump to 'v' selection are bad! 2nd 'v' is NOT SEL.

![Screenshot from 2021-02-23 11-37-48](https://user-images.githubusercontent.com/4154978/108819496-f7bb7300-75cb-11eb-9b16-44b18e06302b.png)

![Screenshot from 2021-02-23 11-37-51](https://user-images.githubusercontent.com/4154978/108819500-fab66380-75cb-11eb-8422-f60f68b73280.png)

@OlehL 
@OlehL  - this is last plugin with @halfbrained 's patch.

**Comment by Alexey-T** [comment]
@halfbrained Can you please verify that my old report?

**Comment by halfbrained** [comment]
``` python
>>> ed.get_carets()
[(12, 3, 13, 3), (3, 3, 2, 3)]
```

selection for the second caret is from `x=3` to `x=2` for some reason, will see what is the problem

**Comment by halfbrained** [comment]
Seems like a CudaText bug, after adding these two markers - on collect I get broken selection

``` python
ed.markers(MARKERS_ADD, x=1, y=0, tag=3, len_x=1, len_y=0)
ed.markers(MARKERS_ADD, x=3, y=0, tag=3, len_x=1, len_y=0)
```

When adding these markers in reverse order - second selection is still backwards, but it works :)

**Comment by Alexey-T** [comment]
I also called

`ed.set_prop(PROP_TAB_COLLECT_MARKERS,True)`

to simulate it. this gives work like in snippets. I see that tab gives 1 selection + 1 no-selection.

**Comment by Alexey-T** [comment]
output shows that carets are NOT sorted!
```
>>> ed.get_carets()
[(12, 3, 13, 3), (3, 3, 2, 3)]
```
added sorting .. seems fixed now..

**Comment by Alexey-T** [comment]
@halfbrained @OlehL How should Cud show multi-selections here, which direction of selections? 2 carets- both forward selection? both backward? IDK

**Comment by halfbrained** [comment]
I would expect left-to-right. And I can't see a reason to do differently.

**Comment by Alexey-T** [comment]
done.
