### ISSUE TITLE
Markus' patch for i18n

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_snippets#23]
@halfbrained 
Can you pls apply this, and check the screenshot?
[patches.zip](https://github.com/CudaText-addons/cuda_snippets/files/6475487/patches.zip)
[plugintranslation.Misc-de_AT.zip](https://github.com/CudaText-addons/cuda_snippets/files/6475492/plugintranslation.Misc-de_AT.zip)

**Comment by halfbrained** [comment]
All is checked, no problems found. 

Thanks, Markus
