### ISSUE TITLE
added snippet text is not saved if you add another one immediately

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_snippets#30]
snippet text is saved only when you press "OK" (closing the dialog)
but not when you add another snippet right away, or make other changes.

suggestions:
- add apply button
- or add message box "snippet is not saved. save changes?"
this message box will pop up on any other change in this dialog.
- or ...

**Comment by Alexey-T** [comment]
Agree, msg box "save changes?" will be nice. Can you give PR?

**Comment by veksha** [comment]
fixed by 696bb72f98eb2d722fccf32797427bfb6935060c
