### ISSUE TITLE
[""] in config.js

### ISSUE THREAD

**Issue by ildarkhasanshin** [CudaText-addons/cuda_snippets#34]
при добавлении/редактировании сниппета для пустого лексера `(none)`
в `config.js` сохраняется `[]`, вместо `[""]`
отчего перестают работать сниппеты для пустого лексера `(none)`
что можно сделать?

https://github.com/CudaText-addons/cuda_snippets/blob/master/dlg_snip_manage.py#L571
https://github.com/CudaText-addons/cuda_snippets/blob/master/dlg_snip_manage.py#L573
т.е. `oldlexes` и `newlexs` получаются `[]`, вместо `[""]`

пока что такой неизящный код работает
```
if not oldlexes and not newlexs:
    newlexs.append("")
```

**Comment by Alexey-T** [comment]
@veksha Could you help here, please? I am out of context. I am working on Cud engine now.

**Comment by veksha** [comment]
what if just remove: "if lex.strip()" on line 573?

**Comment by veksha** [comment]
или добавить "(none)" лексер, вместо "", во всех нужных местах в коде.
